export const titanium = [
  {
    id: '0',
    name: 'Tamjeed Developer',
    image: require('../Assets/Images/tamjeed.png'),
  },
  {
    id: '1',
    name: 'Social Living',
    image: require('../Assets/Images/social.png'),
  },
  {
    id: '2',
    name: 'Tamjeed Developer',
    image: require('../Assets/Images/tamjeed.png'),
  },
  {
    id: '3',
    name: 'Social Living',
    image: require('../Assets/Images/social.png'),
  },
  {
    id: '4',
    name: 'Tamjeed Developer',
    image: require('../Assets/Images/tamjeed.png'),
  },
  {
    id: '5',
    name: 'Social Living',
    image: require('../Assets/Images/social.png'),
  },
];
export const topInventories = [
  {
    id: '0',
    name: 'Tamjeed Developer',
    by: 'Danial babar',
    details:
      'Bahria Town\nTulip Extension\n05 Marla Plot\nPlot 672, 8626, PU Paid, 96 Lacs Each ',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/tamjeed.png'),
  },
  {
    id: '1',
    name: 'Social Living',
    by: 'Danial babar',
    details:
      'Bahria Town\nTulip Extension\n05 Marla Plot\nPlot 672, 8626, PU Paid, 96 Lacs Each ',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/social.png'),
  },
  {
    id: '2',
    name: 'Tamjeed Developer',
    by: 'Danial babar',
    details:
      'Bahria Town\nTulip Extension\n05 Marla Plot\nPlot 672, 8626, PU Paid, 96 Lacs Each ',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/tamjeed.png'),
  },
  {
    id: '3',
    name: 'Social Living',
    by: 'Danial babar',
    details:
      'Bahria Town\nTulip Extension\n05 Marla Plot\nPlot 672, 8626, PU Paid, 96 Lacs Each ',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/social.png'),
  },
  {
    id: '4',
    name: 'Tamjeed Developer',
    by: 'Danial babar',
    details:
      'Bahria Town\nTulip Extension\n05 Marla Plot\nPlot 672, 8626, PU Paid, 96 Lacs Each ',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/tamjeed.png'),
  },
  {
    id: '5',
    name: 'Social Living',
    by: 'Danial babar',
    details:
      'Bahria Town\nTulip Extension\n05 Marla Plot\nPlot 672, 8626, PU Paid, 96 Lacs Each ',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/social.png'),
  },
];
export const topClassified = [
  {
    id: '0',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
  {
    id: '1',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washoom: 2,
    plot: '5 Marla',
  },
  {
    id: '2',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
  {
    id: '3',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
  {
    id: '4',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
  {
    id: '5',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
  {
    id: '6',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
  {
    id: '7',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washoom: 2,
    plot: '5 Marla',
  },
  {
    id: '8',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
  {
    id: '9',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
  {
    id: '10',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    price: '55 Lakh',
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
  {
    id: '11',
    name: 'House for Sale',
    address: 'Tulip Ext. Block, Bahria Town Lahore',
    image: require('../Assets/Images/home1.jpg'),
    bedRoom: 3,
    washroom: 2,
    plot: '5 Marla',
  },
];
export const Featured = [
  {
    id: '0',
    name: 'Victoria City',
    image: require('../Assets/Images/feature1.jpg'),
  },
  {
    id: '1',
    name: 'Elite Homes Toheed Developersy',
    image: require('../Assets/Images/feature1.jpg'),
  },
  {
    id: '2',
    name: 'Victoria City',
    image: require('../Assets/Images/feature1.jpg'),
  },
  {
    id: '3',
    name: 'Elite Homes Toheed Developersy',
    image: require('../Assets/Images/feature1.jpg'),
  },
  {
    id: '4',
    name: 'Victoria City',
    image: require('../Assets/Images/feature1.jpg'),
  },
  {
    id: '5',
    name: 'Elite Homes Toheed Developersy',
    image: require('../Assets/Images/feature1.jpg'),
  },
];
export const News = [
  {
    id: '0',
    name: 'Sumsung  Housing Schem',
    image: require('../Assets/Images/news1.jpg'),
  },
  {
    id: '1',
    name: 'Independence Day of Pakistan',
    image: require('../Assets/Images/news2.jpg'),
  },
  {
    id: '2',
    name: 'Sumsung  Housing Schem',
    image: require('../Assets/Images/news1.jpg'),
  },
  {
    id: '3',
    name: 'Independence Day of Pakistan',
    image: require('../Assets/Images/news2.jpg'),
  },
  {
    id: '4',
    name: 'Sumsung  Housing Schem',
    image: require('../Assets/Images/news1.jpg'),
  },
  {
    id: '5',
    name: 'Independence Day of Pakistan',
    image: require('../Assets/Images/news2.jpg'),
  },
];
